server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/application/**

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/api/housing/**

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
            
