server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee_db

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring:
          json:
            add:
              type:
                headers: false

    template:
      default-topic: visa-workflow-events

  cloud:
    aws:
      region:
        static: us-east-1
#      credentials:
#        access-key: ${AWS_ACCESS_KEY_ID}
#        secret-key: ${AWS_SECRET_ACCESS_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  s3:
    bucket-name: bf-employee-documents-dev

  security:
    ssn-encryption-key: AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=

security:
  jwt:
    token:
      key: ${JWT_SECRET_KEY:ourSecretTokenKeyUsedToJWTMustBeLongEnough}

eureka:
  client:
    enabled: true

  instance:
    prefer-ip-address: true